### ISSUE TITLE
"Kill all enemy" rooms and potential softlock. 

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enemizer#14]
I watched OhheyitsDavid (Twitch streamer) play an Enemizer run that ended in the 'kill five penguins' room in Ice Palace about two weeks ago, where two enemies were moving spikes (unkillable), two enemies were the blobs that come out of the ground, and the last enemy would not spawn. I don't believe he reported the issue or saved the rom, so that example is lost. 

A couple of days ago I created perhaps my fifth Enemizer, and ran into a similar issue. The second room in Mire would not spawn an enemy, although I used Bombos, walked all over the level looking for a blob, and also Googled if I could kill fire sticks or beamos. Over the course of trying to end the run for several more hours, and on my ninth or tenth attempt in clearing the room, I spotted one of Swamp Palace's water skeeters fleeing the top left side of the screen. Bombos was the only way to kill it in this case. 

I know most "kill all enemy" triggers work when a skeeter leaves, but I was surprised that this was clearly the last enemy. I had cleared the room, then went up and down the stairs immediately, as to not respawn the enemies that I had killed. 

[Here is the rom](https://drive.google.com/open?id=0B2Xm3-3XnsGVRjF2bjNCcTZxbDA) where I had last saved it, a long time before I had found the correct solution. Note: this randomizer is Item, Enemy, _and_ entrance, in order to enter Mire you need to **enter Sanctuary's vanilla (light world) entrance**. Sorry, no screenshots or video, my school laptop barely runs SNES9x. 

Knowing what I found in this rom helps me know I can repeatedly try to spawn and kill this enemy, and that this enemy does exist. In the very least I would like to help others know that they are not 100% softlocked by the seed.

**Comment by Zarby89** [comment]
I am aware of that problem in that room i removed all flying enemies from that room but i probably missed that one, i have no idea why the door doesn't open when it fly outside comapred to others rooms it could be because of the stairs or something else, that will be fixed in the next version thanks for reporting bugs :)

**Comment by sosuke3** [comment]
These types of shutter room issues should be fixed
