### ISSUE TITLE
Randomize Enemies Damage not working properly when unchecked

### ISSUE THREAD

**Issue by Ammako** [Zarby89/Enemizer#51]
I left Randomize Enemies Damage unchecked.

Thieves (both LW and DW versions) tend to still deal damage even though I'm *pretty* sure they should just push you around without dealing damage, but most importantly, Ganon basically dealt no damage at all.

Enemizer 6.0.12 - ALttP - VT_no-glitches-27_normal-open-dungeons_271208976 (EN362171639)

Options used:
- Randomize Enemies (WIP)
- Randomize Bush/Grass Enemy Chance
- Randomize Bosses (Type of Randomization: Chaos)
- Shuffle pot contents

Everything else unchecked. "Allow 0 Damage" and "Shuffle Damage Groups" were left checked when I unchecked "Randomize Enemy Damage", in case that could be a potential cause for problems.

I don't recall seeing any enemies other than those three with abnormal damage.

**Comment by Ammako** [comment]
> I don't recall seeing any enemies other than those three with abnormal damage.

Actually no, I remember Kholdstare's three eyes dealt no damage on contact as well, only the falling snowballs.

That makes 4 affected enemies, that I can remember.

**Comment by sosuke3** [comment]
Fixed a couple versions ago but forgot to close this
