### ISSUE TITLE
Garbled Sprites of Tile Throwing Rooms

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enemizer#54]
A very limited number of rooms in the game have thrown tiles: 

- Desert Palace (Boss) room 2*
- Desert Palace (Boss) room 6**
- Tower of Hera Basement
- Misery Mire Torch room
- Ganon's Tower Tile room*

The room with asterisks have garbled sprites, and have with every release of Enemizer V6:
<img width="753" alt="desert tiles" src="https://user-images.githubusercontent.com/17417666/32481897-8c70dd94-c352-11e7-84e0-e99ef7496739.PNG">
<img width="753" alt="gt tiles 2" src="https://user-images.githubusercontent.com/17417666/32481911-9d270f8c-c352-11e7-9d62-9970ac7582a8.PNG">

I thought it also affected the 6th room of the boss area of Desert Palace, but I did find one seed that did not have them garbled. However, here is a garbled example anyways:
<img width="752" alt="desert tiles2" src="https://user-images.githubusercontent.com/17417666/32481949-cda48482-c352-11e7-867c-848236f29378.PNG">

I have never seen the remaining two, Tower of Hera Basement or Misery Mire Torch room, be garbled.

**Comment by sosuke3** [comment]
Should be fixed
