### ISSUE TITLE
Some World Sprites Garbled in 6.0.12

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enemizer#55]
Some places, usually the overworld, have had garbled graphics since the 6.0.12 release.

The three desert statues that block entry into Desert Palace:
<img width="753" alt="desert problems 7" src="https://user-images.githubusercontent.com/17417666/32482840-b45462dc-c356-11e7-89ef-53e4db658825.PNG">

Depending on where you entered desert actually caused the graphics to be different each time.
![desert problems combined](https://user-images.githubusercontent.com/17417666/32482841-b48d8c4c-c356-11e7-904e-f0d1aa1d38af.png)

The Bombos Monolith, also in desert:
<img width="753" alt="monolith3" src="https://user-images.githubusercontent.com/17417666/32483157-f62c5a38-c357-11e7-8ec0-d3b73756deb9.PNG">

The Fat Fairy (or Pyramid Fairy) (Note: the Waterfall Fairy and the Rupee Fairy have normal sprites):
<img width="754" alt="fat fairy" src="https://user-images.githubusercontent.com/17417666/32483078-a20bcbfa-c357-11e7-8b47-0a1b64dcfa53.PNG">

**Comment by sosuke3** [comment]
Should be fixed
