### ISSUE TITLE
Garbled Hidden Enemy Sprites over all Version 6 Releases

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enemizer#56]
At least two enemies have had garbled sprites over all releases of Enemizer, and are still garbled in V6.0.12

The first is the hoarder enemy, specifically the few cases that it appears under a large rock:
<img width="753" alt="rock hoarder" src="https://user-images.githubusercontent.com/17417666/32483529-b105e65c-c359-11e7-9e8e-415150e36e72.PNG">
In this, the above, example, the spike trap next to Link is actually a hoarder that is throwing hearts. The lower spike trap is, in fact, a spike trap. 

This case is somewhat rare, this garbling seems to make these hoarders into spike traps, and not "spazzing sprites" like many of the other garbled sprites do. As an aside, I find that many spike traps during the Mothula fight turn into rock hoarders (or rock hoarder parts) in many seeds: 
<img width="753" alt="spikes" src="https://user-images.githubusercontent.com/17417666/32483673-4908eeea-c35a-11e7-8990-1e1c5f969910.PNG">

The second enemy that is still has garbling is ravens found in bushes (that also immediately run away, unlike some other ravens). Sorry, I didn't circle the garbled raven in any of these shots, but I assume it will be identifiable since all other sprites make sense now:
<img width="752" alt="raven" src="https://user-images.githubusercontent.com/17417666/32484035-b928741a-c35b-11e7-9f7c-99db8fcd8231.PNG">
<img width="753" alt="raven1" src="https://user-images.githubusercontent.com/17417666/32484036-b943a41a-c35b-11e7-81c7-2f93ada24cb3.PNG">
<img width="753" alt="raven2" src="https://user-images.githubusercontent.com/17417666/32484037-b9667774-c35b-11e7-8d70-52844730c220.PNG">
<img width="754" alt="raven3" src="https://user-images.githubusercontent.com/17417666/32484038-ba2a2fca-c35b-11e7-9b16-eb477127f9bb.PNG">

**Comment by sosuke3** [comment]
Should be fixed
