### ISSUE TITLE
[6.0.13] Wallmaster warp, Entrance abnormality

### ISSUE THREAD

**Issue by GB-CG** [Zarby89/Enemizer#59]
[Here's some footage](https://www.youtube.com/watch?v=qwM_G4FYwG4) that occurred while playing the seed 596071109.

Entering the Mysterious Hut, there is a Redead and a Wallmaster. The hand grabbed me and warped me in the same place but with no music and exiting takes me to the Lost woods all screwed up and thinks I'm at the Eastern Palace and unabled to move at all. At least saving & quiting turns it back to normal, and using the Ocarina warps me out of the mess.

Emulator: SNES9x-GX v4.3.7
ROM info: no-glitches-27_normal-standard-ganon_timed-race_753014013 (EN596071109)

**Comment by sosuke3** [comment]
Wallmasters will only show in dungeons now
