### ISSUE TITLE
MSU1 issues

### ISSUE THREAD

**Issue by ghost** [Zarby89/Enemizer#71]
I went through the game using MSU1:

- When you go through Zora whirlpools, the original spc starts playing again alongside the pcm;
- The music doesn't properly stop when you die;
- Fairy fountain music doesn't work right, it only starts once you exit the area;
- File Select music doesn't properly stop when you select a file, and keeps playing through the "continue point select" screen;
- The music doesn't properly stop on Save & Quit;
- The music never does fade-out transitions;
- The music volume never gets lowered when entering houses and on the ocarina fly map;
- When you unlock Ganon's Tower with the 7 Crystals, the original spc for death mountain takes over and pcm stops playing;
- When you die on a boss (in my case, Agahnim in Ganon's Tower) and get revived by a fairy, the original boss music spc starts playing in the background while the pcm is still playing.

Couldn't easily test these last two, but I know the other ones don't happen on vanilla alttp-msu1 (and thus everything works properly.)

This is with higan v105.

**Comment by Ammako** [comment]
@qwertymodo

**Comment by qwertymodo** [comment]
I was just working yesterday on reworking the code to be timing compatible for VT, so there should be an update eventually.  One obvious issue is that you need to use the No BGM option when generating your VT ROM, that's why you're getting a bunch of SPC music playing.

**Comment by sosuke3** [comment]
MSU1 is handled in the base rando rom now and I think most of these issues are fixed.
