### ISSUE TITLE
Unlikely but possible entrapment in ToH entrance

### ISSUE THREAD

**Issue by Songleaves** [Zarby89/Enemizer#88]
If you lack the small key and mirror, and fall down into first room of ToH while the orange blocks are up, and if you lack the means by which to hit the crystal switch (i.e. fire/ice rod, bow, cane of somaria, sword beams) then only way to escape without saving and quitting is to death warp off of enemies.

Right now the possibility exists that you could have three enemies spawn which are unable to damage you. The two dodongos, for instance, can be enemies who lack ranged attacks and are unable to harm you through their cages. The minimoldorm can be a non-damaging enemy such as a thief or bunny beam. If this occurs then the game would force you to save and quit, and reclimb up DM to ToH the long way.

**Comment by sosuke3** [comment]
After getting opinions on this, everyone agreed that this is simply the nature of enemizer and rando in general. You could trap yourself in vanilla if you kill the enemies without thinking, and this isn't the only place you can trap yourself with enemizer.
