### ISSUE TITLE
Late Swamp Palace Enemies Being Set to Vanilla

### ISSUE THREAD

**Issue by EnderofGames** [Zarby89/Enemizer#90]
The Kyameron (Water Bubbles) and Water Tektites (Skeeters) of late Swamp Palace were set to be the only enemies there due to problems, but there still seems to be one or two problems: 

https://clips.twitch.tv/YummyHomelyLettuceFeelsBadMan

In the clip above or image below: the enemies on top of the stair case (same room) don't have to be reverted to the two, since they are not in water. 

<img width="754" alt="7" src="https://user-images.githubusercontent.com/17417666/41131629-cb6be56a-6a79-11e8-93bc-16540a129e6e.PNG">

Then up the stairs (next room, with the thin corridor) the vanilla enemy is the slime that pops out of the ground. After some enemies blocked this corridor (and the next room) it was supposed to be set to vanilla, however it was set instead to the same Skeeters and Bubbles. This might not be a big problem, but they look weird and are still stuck in place like most other enemies are. 

Then the waterway, caught in the end clip, the three Skeeters in vanilla may be enemized into Skeeters or Kyameron. The problem with this is the latter, like most non-skeeter enemies, are invisible. Both this and the problem directly above can be solved by leaving these enemies unrandomized, instead of setting them between Kyameron or Water Tektites. 

Lastly the enemies in the left most room of Swamp (after the second flood room) the enemies are also all set to be Skeeters or Water Bubbles. The first three or so enemies are on land, and should be (re)set to the regular pool of enemies. 

<img width="754" alt="6" src="https://user-images.githubusercontent.com/17417666/41131608-b9698796-6a79-11e8-8650-57fa08dd7d77.PNG">

**Comment by sosuke3** [comment]
Sorry for the late reply. This is on purpose due to a limitation in the current programming. Eventually this will get fixed.

**Comment by EnderofGames** [comment]
To be specific, these enemies are still randomized, they are just randomized to enemies that are common in the Swamp Palace. Stopping the randomization of these enemies (for now) would fix some of the more apparent problems, such as the skeeters always just running offscreen due to being on land, and the invisible water bubbles in the super room just before the boss room.
